---
title: "README"
output: 
  html_document:
    keep_md: yes
---

Materials for manuscript describing drivers of Potamogeton species distribution in temperate lakes

## Data files

* `allmn_wq.RData` Combined legacy and recent STORET wq data for Minnesota lakes that I have aggregated across all dates, created in `storet_proc.R`, further modified in `wq_proc.r` to supplement missing data with DNR fisheries wq data

* `allwi_wq.RData` Combined legacy and recent STORET wq data for Wisconsin lakes that I have aggregated across all dates, created in `storet_proc.R`, further modified in `wq_proc.r` to supplement missing data with LTER WI data

* `legacy_wi_storet_keys.RData` spatial matches of legacy STORET stations and WBIC codes for Wisconsin, used to create wq data in `storet_proc.R`

* `mn_potam.RData` Minnesota data, frequency occurrence of potamogeton species and supporting data for each lake

* `mnmet_dat.RData` Old master dataset for Minnesota from dissertation 

* `new_wi_storet_keys.RData` spatial matches of recent STORET stations and WBIC codes for Wisconsin, used to create wq data in `storet_proc.R`

* `wi_potam.RData` Wisconsin data, frequency occurrence of potamogeton species and supporting data for each lake

* `wimet_dat.RData` Old master dataset for Wisconsin from dissertation

## Data description

Supporting data for each lake include morphometry, water quality, climate, and spatial variables:

* morphometry: lake area (km2), perimeter (km), and max depth (m)

* water quality: alkalinity (mg/L CaCO3), water colour (Pt-Co units), secchi depth (m), and phosphorous (mg/L)

* climate:  annual mean temp (C), maximum temp of warmest month (C), minimum temp of coolest month (C), precip of driest month (mm), and altitude above sea level (m)

* spatial: lat, long

## Data coverage

Not all data are complete for each dataset, mostly water quality data are missing:

```{r}
# MN
data(mn_potam)
dim(mn_potam)
dim(na.omit(mn_potam))
apply(mn_potam, 2, function(x) sum(is.na(x)))
  
# WI
data(wi_potam)
dim(wi_potam)
dim(na.omit(wi_potam))
apply(wi_potam, 2, function(x) sum(is.na(x)))
  
# coverage map complete data
library(maps)
map('state', region = c('wisconsin', 'minnesota'))
points(Latitude ~ Longitude, data = na.omit(mn_potam))
points(Latitude ~ Longitude, data = na.omit(wi_potam)) 

```


